include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - secret-detection
  - deploy

variables:
  SECRET_DETECTION_ENABLED: 'true'

secret_detection:
  stage: secret-detection

deploy-to-caprover:
  stage: deploy
  image: caprover/cli-caprover:latest

  script:
    - echo "Deploy automático para CapRover iniciado..."
    - caprover deploy \
      --caproverUrl $CAPROVER_URL \
      --caproverPassword $CAPROVER_PASSWORD \
      --appName $CAPROVER_APP \
      --imageName $CI_REGISTRY_IMAGE/my-build-image:$CI_COMMIT_SHA

  only:
    - main
